collections_config:
  pages:
    path: src/content
    glob: 
      - '!blog/*'
      - '!authors/*'
    url: /[slug]/
    _enabled_editors:
      - visual
  blog:
    path: src/content/blog
    url: /blog/[slug]/
    _enabled_editors:
      - visual
  authors:
    path: src/content/authors
    url: /authors/[slug]/
    _enabled_editors:
      - visual