# yaml-language-server: $schema=https://raw.githubusercontent.com/CloudCannon/configuration-types/main/cloudcannon-config.schema.json

paths:
  static: public
  uploads: public/images

markdown:
  engine: commonmark
  options:
    gfm: true
    table: true

_editables:
  content:
    blockquote: true
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    image: true
    italic: true
    link: true
    numberedlist: true
    removeformat: true
    snippet: true
    table: true

collections_config:
  pages:
    path: src/content/pages
    glob:
      - "!homes/**"
      - "!landing/**"
    url: "/[slug]/"
    icon: wysiwyg
    _enabled_editors:
      - visual
      - data
    schemas:
      page_builder:
        path: .cloudcannon/schemas/page-builder.md
        name: Page Builder
      default:
        path: .cloudcannon/schemas/page.md
        name: Page
    add_options:
      - name: Page
        schema: default
        icon: wysiwyg
      - name: Page Builder
        schema: page_builder
        icon: dashboard
  homes:
    path: src/content/pages/homes
    url: "/homes/[slug]/"
    icon: wysiwyg
    _enabled_editors:
      - visual
      - data
    schemas:
      page_builder:
        path: .cloudcannon/schemas/page-builder.md
        name: Page Builder
      default:
        path: .cloudcannon/schemas/page.md
        name: Page
    add_options:
      - name: Page
        schema: default
        icon: wysiwyg
      - name: Page Builder
        schema: page_builder
        icon: dashboard
  landing:
    path: src/content/pages/landing
    url: "/landing/[slug]/"
    icon: wysiwyg
    _enabled_editors:
      - visual
      - data
    schemas:
      page_builder:
        path: .cloudcannon/schemas/page-builder.md
        name: Page Builder
      default:
        path: .cloudcannon/schemas/page.md
        name: Page
    add_options:
      - name: Page
        schema: default
        icon: wysiwyg
      - name: Page Builder
        schema: page_builder
        icon: dashboard
  post:
    path: src/data/post
    url: "/[slug]/"
    icon: event_available
    _enabled_editors:
      - content
      - data

data_config:
  navigation:
    path: src/data/navigation.json
  config:
    path: src/config.yaml

collection_groups:
  - heading: Pages
    collections:
      - pages
      - homes
      - landing
  - heading: Blogging
    collections:
      - post
  - heading: Site Settings
    collections:
      - data

_inputs:
  title:
    type: text
  subtitle:
    type: textarea
  tagline:
    type: text
  description:
    type: textarea
  content:
    type: html
    options:
      allow_custom_markup: true
  image:
    type: image
  src:
    type: image
  alt:
    type: text
  icon:
    type: select
    comment: "Pick an icon or type a custom [Iconify](https://icon-sets.iconify.design/) name"
    options:
      allow_create: true
      values:
        - tabler:accessible
        - tabler:adjustments-horizontal
        - tabler:arrow-big-up-lines
        - tabler:arrows-right-left
        - tabler:artboard
        - tabler:article
        - tabler:award
        - tabler:brand-behance
        - tabler:brand-dribbble
        - tabler:brand-pinterest
        - tabler:brand-tailwind
        - tabler:brand-twitter
        - tabler:briefcase
        - tabler:building-store
        - tabler:bulb
        - tabler:carousel-horizontal
        - tabler:check
        - tabler:chevron-right
        - tabler:chevrons-right
        - tabler:chevrons-up
        - tabler:clock
        - tabler:coin
        - tabler:components
        - tabler:download
        - tabler:eyeglass
        - tabler:file-download
        - tabler:flip-vertical
        - tabler:globe
        - tabler:headset
        - tabler:heart
        - tabler:home-star
        - tabler:info-square
        - tabler:layers-union
        - tabler:letter-case
        - tabler:list-check
        - tabler:mail
        - tabler:map-pin
        - tabler:message-circle
        - tabler:message-star
        - tabler:messages
        - tabler:number-1
        - tabler:number-2
        - tabler:number-3
        - tabler:number-4
        - tabler:number-5
        - tabler:number-6
        - tabler:number-7
        - tabler:package
        - tabler:paint
        - tabler:phone
        - tabler:photo
        - tabler:picture-in-picture
        - tabler:plug-connected
        - tabler:podium
        - tabler:presentation
        - tabler:refresh
        - tabler:rocket
        - tabler:school
        - tabler:settings
        - tabler:shield-lock
        - tabler:shopping-cart
        - tabler:square-number-1
        - tabler:square-number-2
        - tabler:square-number-3
        - tabler:square-number-4
        - tabler:square-rounded-arrow-right
        - tabler:stairs
        - tabler:template
        - tabler:tie
        - tabler:user-star
        - tabler:users
        - tabler:vaccine
        - tabler:wand
        - tabler:wifi-off
        - tabler:writing
        - flat-color-icons:advertising
        - flat-color-icons:approval
        - flat-color-icons:business-contact
        - flat-color-icons:currency-exchange
        - flat-color-icons:database
        - flat-color-icons:document
        - flat-color-icons:gallery
        - flat-color-icons:template
        - flat-color-icons:voice-presentation
  href:
    type: url
  isDark:
    type: switch
  isReversed:
    type: switch
  isBeforeContent:
    type: switch
  isAfterContent:
    type: switch
  hasRibbon:
    type: switch
  draft:
    type: switch
  publishDate:
    type: datetime
    instance_value: now
  updateDate:
    type: datetime
  layout:
    type: select
    options:
      values:
        - page
        - landing
    hidden: true
  variant:
    type: select
    options:
      values:
        - primary
        - secondary
        - tertiary
        - link
  _schema:
    type: select
    options:
      values:
        - page_builder
        - default
    hidden: true
  content_blocks:
    type: array
    options:
      structures:
        values_from_glob:
          - /src/components/widgets/*.cloudcannon.structure-value.yml
  metadata:
    type: object
    options:
      preview:
        icon: manage_search
  columns:
    type: number
  rows:
    type: number
  count:
    type: number
  price:
    type: text
  period:
    type: text
  target:
    type: select
    options:
      values:
        - _blank
        - _self
  type:
    type: text

_structures:
  actions:
    values:
      - label: Action
        icon: ads_click
        preview:
          text:
            - key: text
            - Action
          icon:
            - ads_click
        value:
          text:
          href:
          variant: primary
          icon:
          target:
  items:
    values:
      - label: Item
        icon: list
        preview:
          text:
            - key: title
            - Item
          icon:
            - key: icon
            - list
        value:
          title:
          description:
          icon:
  stats:
    values:
      - label: Stat
        icon: bar_chart
        preview:
          text:
            - key: title
            - Stat
          icon:
            - key: icon
            - bar_chart
        value:
          amount:
          title:
          icon:
  prices:
    values:
      - label: Price
        icon: payments
        preview:
          text:
            - key: title
            - Price
          icon:
            - payments
        value:
          title:
          subtitle:
          price:
          period:
          items: []
          callToAction:
            text:
            href:
          hasRibbon: false
          ribbonTitle:
        _inputs:
          hasRibbon:
            type: switch
  testimonials:
    values:
      - label: Testimonial
        icon: format_quote
        preview:
          text:
            - key: name
            - Testimonial
          icon:
            - format_quote
          image:
            - key: image.src
        value:
          testimonial:
          name:
          job:
          image:
            src:
            alt:
  inputs:
    values:
      - label: Input
        icon: input
        preview:
          text:
            - key: label
            - Input
          icon:
            - input
        value:
          type: text
          name:
          label:
          placeholder:
  images:
    values:
      - label: Image
        icon: image
        preview:
          image:
            - key: src
          icon:
            - image
        value:
          src:
          alt:
  header_links:
    values:
      - label: Link
        icon: link
        preview:
          text:
            - key: text
            - Link
          icon:
            - link
        value:
          text:
          href:
      - label: Dropdown
        icon: arrow_drop_down
        preview:
          text:
            - key: text
            - Dropdown
          icon:
            - arrow_drop_down
        value:
          text:
          links: []
  footer_link_groups:
    values:
      - label: Link Group
        icon: folder
        preview:
          text:
            - key: title
            - Link Group
          icon:
            - folder
        value:
          title:
          links: []
  social_links:
    values:
      - label: Social Link
        icon: share
        preview:
          text:
            - key: ariaLabel
            - Social Link
          icon:
            - share
        value:
          ariaLabel:
          icon:
          href:

_snippets:
  logo:
    template: mdx_component
    inline: false
    preview:
      text: Logo
      icon: image
    definitions:
      component_name: Logo
      named_args: []
  youtube:
    template: mdx_component
    inline: false
    preview:
      text: YouTube Video
      icon: play_circle
    definitions:
      component_name: YouTube
      named_args:
        - editor_key: id
          type: string
  tweet:
    template: mdx_component
    inline: false
    preview:
      text: Tweet
      icon: chat
    definitions:
      component_name: Tweet
      named_args:
        - editor_key: id
          type: string
  vimeo:
    template: mdx_component
    inline: false
    preview:
      text: Vimeo Video
      icon: videocam
    definitions:
      component_name: Vimeo
      named_args:
        - editor_key: id
          type: string

file_config:
  - glob: src/config.yaml
    _inputs:
      site:
        type: object
        options:
          preview:
            icon: language
      metadata:
        type: object
        options:
          preview:
            icon: manage_search
      i18n:
        type: object
        options:
          preview:
            icon: translate
      apps:
        type: object
        options:
          preview:
            icon: apps
      analytics:
        type: object
        options:
          preview:
            icon: analytics
      ui:
        type: object
        options:
          preview:
            icon: palette
